version: '3.8'

services:
  db:
    container_name: tyan-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB="${DB_NAME}" 
      - POSTGRES_USER="${DB_USER}"
      - POSTGRES_PASSWORD="${DB_PASSWORD}"
    ports:
      - '4444:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  bot:
    container_name: tyan-bot
    build: .
    image: tyan-bot-image
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      TOKEN: "${TOKEN}"
      DB_HOST: db 
      DB_PORT: "${DB_PORT}" 
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
    links:
      - db

volumes:
  db:
    driver: local